### PR TITLE
Add SOCKS5 proxy support for kubectl exec

### PR DESCRIPTION
**Pull request by TGPSKI**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

The PR permits using kubectl commands like `kubectl exec` via a SOCKS5 proxy. The PR adds support for SOCKS5 proxies, but does not change HTTP or HTTPS behavior.

**Does this PR introduce a user-facing change?**:

```release-note
The PR permits using kubectl commands like `kubectl exec` via a SOCKS5 proxy. 
The PR adds support for SOCKS5 proxies, but does not change HTTP or HTTPS behavior.
```

### CODE REVIEW

**Review by bendrucker — COMMENTED** [review]
Great! I confirmed this builds via `make kubectl` locally, good start.

Two things to discuss:

### Testing

The HTTP proxy tests rely on running an HTTP server for the tests. SOCKS should in theory use something like https://github.com/armon/go-socks5 to do the same. This could be kinda time consuming to write. It would be a good learning exercise but if you don't have time we could see if they'd entertain merging without test coverage.

### Auth

I'm kinda confused by the HTTP proxy auth and the `proxyAuth` method:

https://github.com/TakeScoop/scoop-kubernetes/blob/267a6998eaed8fb296a5916d2a70abccbc3e658f/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go#L286-L294

It's just pulling the username off the URL and not a password. Not super familiar with HTTP proxies but it seems like they accept the same kind of auth format as HTTP basic auth:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization

If the existing code isn't handling passwords, it seems likely that very few users actually need auth of any kind. But it would also be trivial to fix and handle it correctly for both HTTP and SOCKS. Might as well do so to eliminate any need to discuss.

**Comment by TGPSKI** [comment]
Already playing around w/ go-socks5 for test coverage, will take a look at the Auth portion.

Thanks for the guidance.

**Comment by TGPSKI** [comment]
image

**Comment by TGPSKI** [comment]
> If the existing code isn't handling passwords, it seems likely that very few users actually need auth of any kind. But it would also be trivial to fix and handle it correctly for both HTTP and SOCKS. Might as well do so to eliminate any need to discuss.

They are handling passwords here.

`proxyURL.User.String()` returns `username:password`
`proxyURL.User.Username()` returns a string as expected.
`proxyURL.User.Password()` returns password (string), isSet (bool)

**Review by bendrucker — APPROVED** [review]

**Comment by kfox1111** [comment]
Anything missing to get this merged? Seems very useful.

**Comment by TGPSKI** [comment]
> Anything missing to get this merged? Seems very useful.

@kfox111, please see this PR on the main k8s repo: https://github.com/kubernetes/kubernetes/pull/84205

A few things:

1. Please 👍 the PR
2. Need to figure out the SOCKS5 mock proxy server. The two options we have to use are not maintained and the api-machinery folks had some issues using this package as part of the tests. See https://github.com/kubernetes/kubernetes/pull/84205#discussion_r342363339
3. I need to figure out how to add modules to the k8s repo. I have spent significant time trying to find clear documentation on how to add modules, but haven't been able to figure it out yet.

**Pull request closed without merging**
